### ISSUE TITLE
Missing docs about how to run the .blend file

### ISSUE THREAD

**Issue by Dorianux** [AStox/tankbot#1]
Hi!

Very cool- still a basic game, but great to learn!

I am missing a short documentation on how run the game 
after checking out the repository.

**Comment by AStox** [comment]
Hi Dorianux,
Thanks for raising this issue. I realized that not only are you right, there is no proper documentation on how to run the game, but the .blend file supplied was not up-to-date. I've uploaded the newest version of the .blend file and updated the README.md file to include a section on how to run the game in blender or without blender.
I hope this helps, otherwise let me know and I'll do what I can to help!

-Adam
